In [8]:
%pylab inline
import pandas as pd

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

Using $v = c \; (\frac{\Delta \lambda}{\lambda})$

In [21]:
target_list = ['CITau', 'FZTau', 'IQTau', 'AS205', 'DoAr25', 'DoAr33', 'GKTau', 'HD143006', 'HPTau', 'IRAS04385', 'WSB52']

simbad = np.array([0.000056,0.000053,0.000051,0,-0.000042,-0.000020,0,-0.000011,0,0.000054,-0.000018])
manual = np.array([8.287403188972582e-05, 6.167566692537638e-05, 3.9213434436350086e-05, -1.9775651864217518e-05, 6.500960827601571e-05, 4.064045493023696e-09, 3.9435926632100225e-05, -2.4204216721348564e-05, 8.916085557921988e-05, 7.529437390769507e-06, 1.2263509542823756e-05])
med = np.array([9.049851640708842e-05, 5.852846016579358e-05, 2.707268036347967e-05, -1.912968399707197e-05, 5.433825586263136e-05, 1.9642877564928053e-05, 4.511667097231745e-05, -2.367921488979874e-05, 8.81596860666029e-05, 7.529437390769507e-06, -4.562112627455105e-06])

c = 3e5                 #km/s

simbad_redshift = np.round_(c * (simbad * 0.2), 2)
manual_redshift = np.round_(c * (manual * 0.2), 2)
med_redshift = np.round_(c * (med * 0.2), 2)



redshift_data = pd.DataFrame(data={'target':target_list,'simbad_redshift [km/s]':simbad_redshift, 'lineflux_avg_redshift [km/s]':manual_redshift, 'lineflux_med_redshift [km/s]':med_redshift})

redshift_data

,target,simbad_redshift [km/s],lineflux_avg_redshift [km/s],lineflux_med_redshift [km/s]
0,CITau,3.53,5.22,5.70
1,FZTau,3.34,3.89,3.69
2,IQTau,3.21,2.47,1.71
3,AS205,0.00,-1.25,-1.21
4,DoAr25,-2.65,4.10,3.42
5,DoAr33,-1.26,0.00,1.24
6,GKTau,0.00,2.48,2.84
7,HD143006,-0.69,-1.52,-1.49
8,HPTau,0.00,5.62,5.55
9,IRAS04385,3.40,0.47,0.47
10,WSB52,-1.13,0.77,-0.29